package vicMaps

object zoneCodeGroup {

  val zoneCodeGroup: Map[String, String] = Map(
    "ACZ" -> "Special",
    "B1Z" -> "Commercial",
    "B2Z" -> "Commercial",
    "B3Z" -> "Commercial",
    "B4Z" -> "Commercial",
    "B5Z" -> "Commercial",
    "C1Z" -> "Commercial",
    "C2Z" -> "Commercial",
    "CA" -> "Special",
    "CCZ" -> "MixedUse",
    "CDZ" -> "Special",
    "DZ" -> "MixedUse",
    "FZ" -> "Agriculture",
    "GRZ" -> "Residential",
    "GWAZ" -> "OpenSpace",
    "GWZ" -> "OpenSpace",
    "GWZA" -> "OpenSpace",
    "IN1Z" -> "Industrial",
    "IN2Z" -> "Industrial",
    "IN3Z" -> "Industrial",
    "LDRZ" -> "Residential",
    "MUZ" -> "MixedUse",
    "NRZ" -> "Residential",
    "PCRZ" -> "OpenSpace",
    "PDZ" -> "Special",
    "PPRZ" -> "OpenSpace",
    "PUZ1" -> "Institutional",
    "PUZ2" -> "Institutional",
    "PUZ3" -> "Institutional",
    "PUZ4" -> "Institutional",
    "PUZ5" -> "Institutional",
    "PUZ6" -> "Institutional",
    "PUZ7" -> "Institutional",
    "R1Z" -> "Residential",
    "R2Z" -> "Residential",
    "R3Z" -> "Residential",
    "RAZ" -> "OpenSpace",
    "RCZ" -> "OpenSpace",
    "RDZ1" -> "Transport",
    "RDZ2" -> "Transport",
    "RGZ" -> "Residential",
    "RLZ" -> "Agriculture",
    "SUZ" -> "Special",
    "TZ" -> "Special",
    "UFZ" -> "Special",
    "UGZ" -> "Special"
  )

}
