package CWW

object meterTypeCleanse {

  val meterTypesCleanse: Map[List[String], List[String]] = Map(

    List("20", "SOCAM", "501AS") -> List("20", "SOCAM", "501AS"),
    List("20", "EMAIL", "E20") -> List("20", "EMAIL", "E20"),
    List("20", "DAVIES SHEPHARD", "ENGLISH CLASS 3 PSM") -> List("20", "Elster", "ENGLISH CLASS 3 PSM"),
    List("20", "EMAIL", "IP20") -> List("20", "EMAIL", "IP20"),
    List("20", "DAVIES SHEPHARD", "KG4") -> List("20", "Elster", "KG4"),
    List("20", "DAVIES SHEPHARD", "KGG") -> List("20", "Elster", "KGG"),
    List("20", "RMC", "MNK WET DIAL") -> List("20", "RMC", "MNK WET DIAL"),
    List("20", "RMC", "MRP PROTECTED ROLLER") -> List("20", "RMC", "MRP PROTECTED ROLLER"),
    List("20", "DAVIES SHEPHARD", "PSM LT (DUAL CHECK)") -> List("20", "Elster", "V100 (DUAL CHECK)"),
    List("20", "DAVIES SHEPHARD", "PSM LT (SINGLE CHECK)") -> List("20", "Elster", "V100 (SINGLE CHECK)"),
    List("20", "DAVIES SHEPHARD", "PSM T") -> List("20", "Elster", "V100 (PSM-T)"),
    List("20", "Actaris", "TD8") -> List("20", "Itron", "TD8"),
    List("20", "ACTARIS SCHLUMBERGER", "TD8") -> List("20", "Itron", "TD8"),
    List("20", "Itron", "TD8") -> List("20", "Itron", "TD8"),
    List("20", "SCHLUMBERGER", "TD8 FIRE SERVICE") -> List("20", "Itron", "TD8 FIRE SERVICE"),
    List("20", "Elster", "V100 (PSM-T)") -> List("20", "Elster", "V100 (PSM-T)"),
    List("25", "RMC", "MNK WET DIAL") -> List("25", "RMC", "MNK WET DIAL"),
    List("25", "DAVIES SHEPHARD", "PSM LT (DUAL CHECK)") -> List("25", "Elster", "V100 (DUAL CHECK)"),
    List("25", "DAVIES SHEPHARD", "PSM T") -> List("25", "Elster", "V100 (PSM-T)"),
    List("25", "Actaris", "TD8") -> List("25", "Itron", "TD8"),
    List("25", "Itron", "TD8") -> List("25", "Itron", "TD8"),
    List("25", "SCHLUMBERGER", "TD8") -> List("25", "Itron", "TD8"),
    List("25", "SCHLUMBERGER", "TD8 FIRE SERVICE METER") -> List("25", "Itron", "TD8 FIRE SERVICE"),
    List("25", "Elster", "V100 (PSM-T)") -> List("25", "Elster", "V100 (PSM-T)"),
    List("32", "RMC", "MULTI JET") -> List("32", "RMC", "MULTI JET"),
    List("32", "DAVIES SHEPHARD", "PSM T") -> List("32", "Elster", "V100 (PSM-T)"),
    List("32", "ACTARIS SCHLUMBERGER", "TD8") -> List("32", "Itron", "TD8"),
    List("32", "Itron", "TD8") -> List("32", "Itron", "TD8"),
    List("32", "Elster", "V100 (PSM-T)") -> List("32", "Elster", "V100 (PSM-T)"),
    List("40", "Itron", "Flostar M") -> List("40", "Itron", "Flostar M"),
    List("40", "ACTARIS SCHLUMBERGER", "FLOWSTAR") -> List("40", "Itron", "Flostar M"),
    List("40", "DAVIES SHEPHARD", "HELIX 3000") -> List("40", "Elster", "HELIX 3000"),
    List("40", "RMC", "MNK WET DIAL") -> List("40", "RMC", "MNK WET DIAL"),
    List("40", "DAVIES SHEPHARD", "PSM T") -> List("40", "Elster", "V100 (PSM-T)"),
    List("40", "Elster", "V100 (PSM-T)") -> List("40", "Elster", "V100 (PSM-T)"),
    List("50", "MEINECKE", "COSMOS C & CD") -> List("50", "MEINECKE", "COSMOS C & CD"),
    List("50", "Itron", "Flostar M") -> List("50", "Itron", "Flostar M"),
    List("50", "SCHLUMBERGER", "FLOWSTAR") -> List("50", "Itron", "Flostar M"),
    List("50", "DAVIES SHEPHARD", "KG2000") -> List("50", "Elster", "V300"),
    List("50", "DAVIES SHEPHARD", "KG4") -> List("50", "Elster", "V300"),
    List("50", "Sensus", "MeiStream Plus") -> List("50", "Sensus", "MeiStream Plus"),
    List("50", "Elster", "V300 (KG 2000)") -> List("50", "Elster", "V300"),
    List("80", "ACTARIS SCHLUMBERGER", "FLOWSTAR") -> List("80", "Itron", "Flostar M"),
    List("80", "Siemens", "MAG8000") -> List("80", "Siemens", "MAG8000"),
    List("80", "Sensus", "MeiStream Plus") -> List("80", "Sensus", "MeiStream Plus"),
    List("100", "MEINECKE", "COSMOS WP") -> List("100", "MEINECKE", "COSMOS WP"),
    List("100", "Itron", "Flostar M") -> List("100", "Itron", "Flostar M"),
    List("100", "DAVIES SHEPHARD", "HELIX 4000") -> List("100", "Elster", "H4000"),
    List("100", "Siemens", "MAG8000") -> List("100", "Siemens", "MAG8000"),
    List("100", "SEIMENS", "Magflow 8000 Battery Compact Ver") -> List("100", "Siemens", "MAG8000"),
    List("150", "ABB", "AQUAMASTER") -> List("150", "ABB", "AQUAMASTER"),
    List("150", "Itron", "Flostar M") -> List("150", "Itron", "Flostar M"),
    List("150", "Siemens", "MAG8000") -> List("150", "Siemens", "MAG8000"),
    List("150", "SEIMENS", "Magflow 8000 Battery Compact Ver") -> List("150", "Siemens", "MAG8000"),
    List("150", "Sensus", "MeiStream Plus") -> List("150", "Sensus", "MeiStream Plus"),
    List("150", "Krohne", "Waterflux") -> List("150", "Krohne", "Waterflux")
  )

}
